version: '3'

services:
  db:
    image: mysql:8.0.29
    container_name: magento_two_mysql
    restart: always
    ports:
      - 3300:3300
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - db:/var/lib/mysql
    networks:
      net:
        ipv4_address: 175.0.0.2

  phpmyadmin:
    image: phpmyadmin
    container_name: magento_two_phpmyadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    links:
      - db
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 175.0.0.3

  app:
    image: nginx:1.23
    container_name: magento_two_nginx
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      net:
        ipv4_address: 175.0.0.4

  php:
    image: magento_two_php
    container_name: magento_two_php
    build: ./.docker/php
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/ini/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
    working_dir: /var/www/html
    links:
      - db
    depends_on:
      - db
      - app
    networks:
      net:
        ipv4_address: 175.0.0.5

  redis:
    image: redis:6.2.8
    container_name: magento_two_redis
    networks:
      net:
        ipv4_address: 175.0.0.6

  rabbitmq:
    image: rabbitmq:3.11.5-management
    container_name: magento_two_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento
    networks:
      net:
        ipv4_address: 175.0.0.7

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: magento_two_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      cluster.name: docker-elasticsearch
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: false
    volumes:
      - ./.docker/elastic:/usr/share/elasticsearch/data
    networks:
      net:
        ipv4_address: 175.0.0.8

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 175.0.0.0/24
          gateway: 175.0.0.1

volumes:
  db:
